### PR TITLE
[lua-monitoring] Reindent lua #13

### LINKED ISSUE #13: [lua-monitoring] Reindent lua
Reindent lua code in a consistent way (4 spaces).

### PR DESCRIPTION
**Pull request by Purhan**
Closes #13

### CODE REVIEW

**Review by nemesisdesign — COMMENTED** [review]
Looks good, will test it asap

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
One request: can you rebase on the current master to avoid overwriting this fix? https://github.com/openwisp/lua-monitoring/commit/fa695565de070c180521b4996be460d5e321f7df

**Comment by Purhan** [comment]
@nemesisdesign done

**Review by nemesisdesign — APPROVED** [review]
Thanks! :+1:

**Pull request merged**
